server:
  port: 8086
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/test.db
  redis:
    database: 6
    port: 6379
    host: 127.0.0.1
mybatis:
  mapper-locations: classpath:mapper/*.xml